WIP: [BIRD-T-41] Match page's
hiddentityfr/bird pull request #16
Opened 2021-06-09 09:53 UTC by PixDay

2021-06-10 04:18 UTC, shellbear commented
#### 📝Changed routes:


| [**/candidates**](https://bird-bvz84dbdq-hiddentity.vercel.app/candidates) |
|:-:|
|<a href="https://bird-bvz84dbdq-hiddentity.vercel.app/candidates"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/9zAqhdxKjuB2PJpfyjCfQBKZUBOhWSivZs1Alps-KBfu9NjmUjZnobfMNLhJlf1bkt572JD40rRqACArYEpulg.png&w=600" alt="Screenshot of /candidates" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/2treP_anpN2sIydR7Uq9wGsmRj8UYALP6PGcI8-gwt49xj9Pso0ifdyZp_7ksTddkdIA0D7EAn6U7MVJQtOuWg.png">(view full size)</a> |







Commit 664bcac1f94466f7e3a7153aca54e587a14a7345 (https://bird-bvz84dbdq-hiddentity.vercel.app).

2021-06-10 04:37 UTC, ysainson requested changes

2021-06-10 04:37 UTC, ysainson commented on components/DataDisplay/Card/match.tsx
> +    <Container gap={0} flex="0 30%">
Évite les % si possible, regarde le composant `OfferCard` dans `components/DataDisplay/Card/offer.tsx`

2021-06-12 20:22 UTC, PixDay commented on components/DataDisplay/Card/match.tsx
> +    <Container gap={0} flex="0 30%">
Oui je vais les enlever c'était mon ancienne `card` je vais déplacer le composant et l'éditer et mettre la requette ce soir @ysainson

2021-06-16 07:12 UTC, ysainson approved these changes

2021-06-16 07:13 UTC, merged